/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weliyek;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WkLibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        WkLibrary classUnderTest = new WkLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
